development:
  adapter: postgresql
  database: dk_db_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: dk_db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dk_db_prod
  pool: 5
  timeout: 5000